
import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';import{templeProfiles}from'./data/templeProfiles.js';import{getHolyEvents}from'./engine/holyDayEngine.js';import{dateKey,dynamicPractice,getMoonPhase,getTibetanDate,sameDate}from'./engine/calendarEngine.js';
const week=['星期日','星期一','星期二','星期三','星期四','星期五','星期六'];
function maskStyle(p){const pct=p[2];if(pct===100)return{display:'none'};if(pct===0)return{width:'100%',left:0};return{width:`${100-pct}%`,left:pct>50?'0':'auto',right:pct<=50?'0':'auto'}}
function Card({title,children,full}){return <section className={'card '+(full?'full':'')}><div className="title">{title}</div><div className="body">{children}</div></section>}
function Tags({arr}){return <div className="tags">{arr.map((x,i)=><span className="tag" key={i}>{x}</span>)}</div>}
function Line({label,value}){return <div className="line"><span className="label">{label}</span><span>{value}</span></div>}
function App(){const[date,setDate]=useState(new Date()),[view,setView]=useState(new Date()),[note,setNote]=useState(''),[profileId,setProfileId]=useState(localStorage.getItem('templeProfile')||'common'),[calendarColor,setCalendarColor]=useState(localStorage.getItem('calendarText')||'#f5f0e7');useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js').catch(()=>{})},[]);useEffect(()=>{setNote(localStorage.getItem('note-'+dateKey(date))||'')},[date]);useEffect(()=>{localStorage.setItem('templeProfile',profileId)},[profileId]);useEffect(()=>{document.documentElement.style.setProperty('--calendarText',calendarColor);localStorage.setItem('calendarText',calendarColor)},[calendarColor]);const profile=templeProfiles[profileId]||templeProfiles.common,tibetan=getTibetanDate(date),moon=getMoonPhase(date),events=getHolyEvents(tibetan,date,profile),practice=dynamicPractice(events,moon,tibetan,profile),main=events[0]||{name:'平常修行日',multiplier:'1x',good:practice,note:'今日無特殊佛日標記，可作穩定日課。'},eventNames=events.length?events.map(e=>e.name).join('、'):'無特殊標記';
function days(){const y=view.getFullYear(),m=view.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),out=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const t=getTibetanDate(d),ev=getHolyEvents(t,d,profile);out.push(<div key={i} className={'day '+(d.getMonth()!==m?'out ':'')+(sameDate(d,date)?'selected ':'')} onClick={()=>{setDate(d);setView(new Date(d.getFullYear(),d.getMonth(),1))}}><div className="solar">{d.getDate()}</div><div className="mini">藏曆{t.month}月{t.day}日</div>{ev[0]&&<span className="badge">{ev[0].name}</span>}</div>)}return out}
return <div className="app"><header className="top"><div className="brand"><h1>今日藏曆 v4 Beta Fixed</h1><p>寺院校正・傳承切換・佛日完整邏輯</p></div><button onClick={()=>{setDate(new Date());setView(new Date())}}>回到今日</button></header><div className="grid">
<Card title="今日國曆"><div className="hero">{dateKey(date).replaceAll('-','.')}</div><div className="sub">{week[date.getDay()]}</div></Card>
<Card title="今日藏曆"><div className="hero">{tibetan.month}月{tibetan.day}日</div><div className="sub">第 {tibetan.cycle} 饒迥｜第 {tibetan.year} 年 {tibetan.leapMonth?'｜閏月':''}{tibetan.leapDay?'｜重日':''}</div><div className="source">核心：{tibetan.source}</div></Card>
<Card title="傳承／寺院資料版本" full><select value={profileId} onChange={e=>setProfileId(e.target.value)}>{Object.values(templeProfiles).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><p className="sub">{profile.description}</p></Card>
<Card title="月亮盈缺動畫" full><div className="moon-card"><div className="moon-wrap"><div className="halo"></div><div className="moon"><div className="moon-mask" style={maskStyle(moon)}></div></div></div><div><div className="hero">{moon[0]}</div><div className="sub">{moon[1]}。亮度約 {moon[2]}%。</div><div className="bar"><span style={{width:moon[2]+'%'}}></span></div></div></div></Card>
<Card title="功德倍率日／佛日" full><div className="grid"><div><div className="sub">{main.name}</div><div className="mult">{main.multiplier}</div><p className="sub">{main.note}</p></div><div><Tags arr={main.good||practice}/><p className="sub">重要法會與功德倍率日仍建議依寺院年曆校正。</p></div></div></Card>
<Card title="今日動態修行建議" full><div className="rec-grid">{practice.map(x=><div className="rec" key={x}>{x}</div>)}</div></Card>
<Card title="月曆顯示設定" full><label>簡易月曆字體顏色 </label><input type="color" value={calendarColor} onChange={e=>setCalendarColor(e.target.value)}/><p className="sub">避免更換背景或主題後文字不清楚。</p></Card>
<section className="card full"><div className="title">月曆</div><div className="month-top"><button onClick={()=>setView(new Date(view.getFullYear(),view.getMonth()-1,1))}>上一月</button><div className="month-title">{view.getFullYear()} 年 {view.getMonth()+1} 月</div><button onClick={()=>setView(new Date(view.getFullYear(),view.getMonth()+1,1))}>下一月</button></div><div className="week">{['日','一','二','三','四','五','六'].map(x=><div key={x}>{x}</div>)}</div><div className="days">{days()}</div></section>
<Card title="詳細資料架構" full><div className="detail-grid"><div className="box"><h3>藏曆核心</h3><Line label="月份" value={tibetan.month}/><Line label="日期" value={tibetan.day}/><Line label="來源" value={tibetan.source}/></div><div className="box"><h3>傳承版本</h3><Line label="版本" value={profile.name}/><Line label="本日事件" value={eventNames}/><Line label="本日套用" value={practice.join('、')}/></div><div className="box"><h3>寺院校正</h3><Line label="資料版本" value={profile.name}/><Line label="校正狀態" value={events.some(e=>e.type==='templeCorrection')?'本日有寺院校正資料':'本日無寺院校正資料'}/></div></div></Card>
<Card title="修行記事" full><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="記錄今日持咒、供燈、供水、靜坐、發願……"/><p><button onClick={()=>localStorage.setItem('note-'+dateKey(date),note)}>儲存</button></p></Card>
</div></div>}
createRoot(document.getElementById('root')).render(<App/>);
